### PR TITLE
Created screen control

### PR DESCRIPTION
**Pull request by nathanajah**
Questions:
How should we use common components / layouts / reducers / store / actions?
Should we just remove layouts (since our layout are not stateless anyway) and just put everything in components / containers?

### CODE REVIEW

**Comment by kevinluvian** [comment]
I think we should only have presentational component for common components / layouts, and use the reducer / store / actions from respective route / app

I personally think we need layout, as by its definition (Components that dictate major page structure), it can't be inserted into neither component nor container. however, if our layout is not stateless, I think it is better to just remove the layout definition, and add it as container (or we can change our definition that layout is "Container that dictate major page structure")

**Comment by nathanajah** [comment]
@kevinluvian 

> I think we should only have presentational component for common components / layouts, and use the reducer / store / actions from respective route / app

However, this would mean that we'll need to duplicate the reducer / store code between apps when we introduce other apps later (uriel etc), right?

> I think it is better to just remove the layout definition, and add it as container (or we can change our definition that layout is "Container that dictate major page structure")

Another possibility is to add layoutcontainers for containerized layouts... it's a bit ugly though ._.

**Comment by nathanajah** [comment]
Oh, anyway, the reason why our page layout is not stateless is because we have features like full screen and sidebar hiding that needs state.

**Comment by kevinluvian** [comment]
> However, this would mean that we'll need to duplicate the reducer / store code between apps when we introduce other apps later (uriel etc), right?

yeah, depends on the design though, do we want to keep multiple state for one common component in the same time on different app?
like for example, there are programming problem in app A and app B
after I put some code when I open app A problem 1, when I open app B problem 1, the editor should be empty, but when I open app A again, do I want the unsaved code still there? (this is random and bad example, it can be solved by just save the code when moving app, but i hope my message is delivered)
if we do want to have multiple state with same component(common component), we need to differentiate the reducer by app. if we don't, we can just have a global common reducer

**Comment by nathanajah** [comment]
> the editor should be empty, but when I open app A again, do I want the unsaved code still there?

Actually with the current judgels structure, the app are served by different servlets. If we use the same structure, then we can't share state between different apps as they will be compiled to different apps. So... I'm still not sure what should we do here. @vincentsthe might be able to give some insight to the current architecture?

**Comment by nathanajah** [comment]
Actually.. What do you think if we only have components / layouts in commons, but we need to containerize it in each app? That way we're not tying any state to apps. We can have reducers / actions inside commons (think of it as a reusable building block), but we still need to containerize it in each app.

This way, we can keep common building blocks stateless, and we can minimize code duplication (The only duplication that we need is the wiring from the common components / reducers to each apps container / store).

**Comment by kevinluvian** [comment]
looks good to me, maybe others can comment on it too

**Pull request merged**
